export const Size = {
  FULLNAME_MIN_LENGTH: 3,
  FULLNAME_MAX_LENGTH: 60,
  EMAIL_MIN_LENGTH: 3,
  EMAIL_MAX_LENGTH: 45,
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 45,
  SCHOOL_NAME_MIN_LENGTH: 6,
  SCHOOL_NAME_MAX_LENGTH: 45,
};
